disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Secure The Throne"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "My_logo-background-less.png"
description = "A Cybersecurity Blog"
author = { name = "Emp5r0R", image = "My-Picture.jpeg", headline = "Lead By Curiosity", bio = "Born to learn", links = [ { htb = "https://app.hackthebox.com/profile/1652264" }, { thm= "https://tryhackme.com/p/Emp5r0R" }, { github = "https://github.com/Emp5r0R" }, { discord = "https://discord.com/users/1221148367707443353"} ] }
secondaryLogo = "My_logo-background-less.png"
enableEmoji = true

[author]
links = []
