[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "GYKn0An81l"
weight = 1

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "TMAl0xcxjF"
weight = 2

[[main]]
name = "About"
pageRef = "about"
identifier = "YZmORBM0hj"
weight = 3

[[main]]
name = "Banana Cracker"
url = "https://github.com/Emp5r0R/BananaCracker"
parent = "Tools"
weight = 999

[[footer]]
none = "none"
