[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "GYKn0An81l"
weight = 9999

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "TMAl0xcxjF"
weight = 9999

[[footer]]
none = "none"
